package rateguard

import (
	"bytes"
	"crypto/ed25519"
	"encoding/csv"
	"encoding/hex"
	"encoding/json"
	"os"
	"strings"
	"testing"
	"time"
)

func receiptTestKey(t *testing.T) (ed25519.PublicKey, ed25519.PrivateKey) {
	t.Helper()
	// Deterministic seed so signatures are reproducible across runs and
	// languages (Ed25519 signing is deterministic by construction).
	seed := make([]byte, ed25519.SeedSize)
	for i := range seed {
		seed[i] = byte(i)
	}
	priv := ed25519.NewKeyFromSeed(seed)
	return priv.Public().(ed25519.PublicKey), priv
}

func sampleClaims() SpendReceiptClaims {
	return SpendReceiptClaims{
		Key:                   "tenant-a:agent-7",
		Provider:              "openai",
		Model:                 "gpt-4o",
		WindowStartUnix:       1_780_000_000,
		WindowEndUnix:         1_780_003_600,
		InputTokens:           120_000,
		OutputTokens:          34_500,
		TotalTokens:           154_500,
		EstimatedCostMicroUSD: 645_000, // $0.645
		PolicyPreset:          "agent-orchestrator",
		AttestationTokenID:    "att-9f2c",
	}
}

func TestSpendReceiptIssueVerifyRoundtrip(t *testing.T) {
	pub, priv := receiptTestKey(t)
	r, err := IssueSpendReceipt(priv, sampleClaims())
	if err != nil {
		t.Fatalf("issue: %v", err)
	}
	if err := VerifySpendReceipt(pub, r); err != nil {
		t.Fatalf("verify: %v", err)
	}

	// JSON transport roundtrip must preserve verifiability.
	raw, err := json.Marshal(r)
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}
	var back SpendReceipt
	if err := json.Unmarshal(raw, &back); err != nil {
		t.Fatalf("unmarshal: %v", err)
	}
	if err := VerifySpendReceipt(pub, &back); err != nil {
		t.Fatalf("verify after JSON roundtrip: %v", err)
	}
}

func TestSpendReceiptTamperDetection(t *testing.T) {
	pub, priv := receiptTestKey(t)
	r, err := IssueSpendReceipt(priv, sampleClaims())
	if err != nil {
		t.Fatal(err)
	}

	tampered := *r
	tampered.Claims.TotalTokens = 1 // claim less spend than signed
	if err := VerifySpendReceipt(pub, &tampered); err == nil {
		t.Fatal("tampered claims must fail verification")
	}

	tampered = *r
	tampered.IssuedAtUnix++
	if err := VerifySpendReceipt(pub, &tampered); err == nil {
		t.Fatal("tampered issue time must fail verification")
	}

	// A different trusted issuer must be rejected before signature math.
	otherPub, _, _ := ed25519.GenerateKey(nil)
	if err := VerifySpendReceipt(otherPub, r); err == nil {
		t.Fatal("wrong trusted issuer must fail")
	}

	// nil trusted issuer = integrity-only mode: passes for the untampered
	// receipt, still fails for a tampered one.
	if err := VerifySpendReceipt(nil, r); err != nil {
		t.Fatalf("integrity-only verify: %v", err)
	}
	tampered = *r
	tampered.Claims.Key = "someone-else"
	if err := VerifySpendReceipt(nil, &tampered); err == nil {
		t.Fatal("integrity-only mode must still detect tampering")
	}
}

func TestSpendReceiptClaimValidation(t *testing.T) {
	_, priv := receiptTestKey(t)

	c := sampleClaims()
	c.Key = ""
	if _, err := IssueSpendReceipt(priv, c); err == nil {
		t.Fatal("empty key must be rejected")
	}

	c = sampleClaims()
	c.WindowEndUnix = c.WindowStartUnix
	if _, err := IssueSpendReceipt(priv, c); err == nil {
		t.Fatal("empty window must be rejected")
	}

	c = sampleClaims()
	c.EstimatedCostMicroUSD = -1
	if _, err := IssueSpendReceipt(priv, c); err == nil {
		t.Fatal("negative cost must be rejected")
	}

	if _, err := IssueSpendReceipt(ed25519.PrivateKey{0x01}, sampleClaims()); err == nil {
		t.Fatal("malformed private key must be rejected")
	}
}

// ── Conformance: byte-exact payload + signature across all 3 SDKs ──

// TestGenerateReceiptVectors regenerates the conformance file from this
// (reference) implementation. Gated so a normal run never rewrites it:
//   RATEGUARD_GENERATE_VECTORS=1 go test -run GenerateReceiptVectors .
func TestGenerateReceiptVectors(t *testing.T) {
	if os.Getenv("RATEGUARD_GENERATE_VECTORS") == "" {
		t.Skip("RATEGUARD_GENERATE_VECTORS not set")
	}
	seed := make([]byte, ed25519.SeedSize)
	for i := range seed {
		seed[i] = byte(i)
	}
	priv := ed25519.NewKeyFromSeed(seed)
	pub := priv.Public().(ed25519.PublicKey)
	claims := sampleClaims()
	issuedAt := int64(1_780_003_700)

	r, err := IssueSpendReceiptAt(priv, claims, time.Unix(issuedAt, 0))
	if err != nil {
		t.Fatal(err)
	}
	out := map[string]any{
		"note":           "Generated by the Go reference implementation (spend_receipt_test.go). All 3 SDKs must reproduce payload and signature byte-for-byte. The seed is a TEST key — never use in production.",
		"seed_hex":       hex.EncodeToString(seed),
		"issued_at_unix": issuedAt,
		"claims":         claims,
		"payload":        string(receiptSigningPayload(claims, issuedAt, pub)),
		"signature_hex":  hex.EncodeToString(r.Signature),
	}
	enc, err := json.MarshalIndent(out, "", " ")
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile("../../conformance/spend_receipt_vectors.json", append(enc, '\n'), 0o644); err != nil {
		t.Fatal(err)
	}
	t.Logf("wrote conformance/spend_receipt_vectors.json (%d bytes)", len(enc))
}

type receiptVectors struct {
	SeedHex      string             `json:"seed_hex"`
	IssuedAtUnix int64              `json:"issued_at_unix"`
	Claims       SpendReceiptClaims `json:"claims"`
	Payload      string             `json:"payload"`
	SignatureHex string             `json:"signature_hex"`
}

func TestSpendReceiptConformanceVectors(t *testing.T) {
	raw, err := os.ReadFile("../../conformance/spend_receipt_vectors.json")
	if err != nil {
		t.Fatalf("read vectors: %v", err)
	}
	var v receiptVectors
	if err := json.Unmarshal(raw, &v); err != nil {
		t.Fatalf("parse vectors: %v", err)
	}

	seed, err := hex.DecodeString(v.SeedHex)
	if err != nil || len(seed) != ed25519.SeedSize {
		t.Fatalf("bad seed in vectors: %v", err)
	}
	priv := ed25519.NewKeyFromSeed(seed)
	pub := priv.Public().(ed25519.PublicKey)

	payload := receiptSigningPayload(v.Claims, v.IssuedAtUnix, pub)
	if string(payload) != v.Payload {
		t.Fatalf("payload mismatch:\n got %s\nwant %s", payload, v.Payload)
	}

	r, err := IssueSpendReceiptAt(priv, v.Claims, time.Unix(v.IssuedAtUnix, 0))
	if err != nil {
		t.Fatal(err)
	}
	if got := hex.EncodeToString(r.Signature); got != v.SignatureHex {
		t.Fatalf("signature mismatch:\n got %s\nwant %s", got, v.SignatureHex)
	}
	if err := VerifySpendReceipt(pub, r); err != nil {
		t.Fatal(err)
	}
}

// ── FOCUS export ──

func TestFOCUSExport(t *testing.T) {
	_, priv := receiptTestKey(t)
	r, err := IssueSpendReceiptAt(priv, sampleClaims(), time.Unix(1_780_003_700, 0))
	if err != nil {
		t.Fatal(err)
	}

	var buf bytes.Buffer
	if err := WriteFOCUSCSV(&buf, []FOCUSRow{FOCUSRowFromReceipt(r)}); err != nil {
		t.Fatalf("write csv: %v", err)
	}

	records, err := csv.NewReader(strings.NewReader(buf.String())).ReadAll()
	if err != nil {
		t.Fatalf("csv must parse back cleanly: %v", err)
	}
	if len(records) != 2 {
		t.Fatalf("want header + 1 row, got %d records", len(records))
	}

	header, row := records[0], records[1]
	col := func(name string) string {
		for i, h := range header {
			if h == name {
				return row[i]
			}
		}
		t.Fatalf("missing FOCUS column %q", name)
		return ""
	}

	if got := col("EffectiveCost"); got != "0.645" {
		t.Fatalf("EffectiveCost = %q, want 0.645 (micro-USD conversion)", got)
	}
	if got := col("BilledCost"); got != "0" {
		t.Fatalf("BilledCost = %q — RateGuard bills nothing, must be 0", got)
	}
	if got := col("ConsumedQuantity"); got != "154500" {
		t.Fatalf("ConsumedQuantity = %q, want 154500", got)
	}
	if got := col("ConsumedUnit"); got != "tokens" {
		t.Fatalf("ConsumedUnit = %q", got)
	}
	if got := col("ChargePeriodStart"); got != "2026-05-28T20:26:40Z" {
		t.Fatalf("ChargePeriodStart = %q", got)
	}
	if got := col("ServiceCategory"); got != "AI and Machine Learning" {
		t.Fatalf("ServiceCategory = %q", got)
	}
	if got := col("x_rateguard_input_tokens"); got != "120000" {
		t.Fatalf("x_rateguard_input_tokens = %q", got)
	}
	if col("x_rateguard_receipt_signature") == "" {
		t.Fatal("receipt signature column must tie the row to its receipt")
	}
}
