apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: rateguard
  namespace: default
  labels:
    app: rateguard
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: rateguard
