package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type SchemaDef struct {
	JSON map[string]any
	TS   string
}

type ParamDef struct {
	Name        string
	In          string
	Required    bool
	Type        string
	Description string
}

type EndpointDef struct {
	Method         string
	Path           string
	OperationID    string
	MethodName     string
	Summary        string
	Description    string
	Tag            string
	RequestSchema  string
	ResponseSchema string
	SuccessStatus  string
	Auth           bool
	Idempotency    bool
	Deprecated     bool
	Params         []ParamDef
}

type artifactSet struct {
	Schemas   map[string]SchemaDef
	Endpoints []EndpointDef
}

// Build returns the OpenAPI document as a JSON-compatible map.
func Build() (map[string]any, error) {
	manifest := manifest()
	schemaJSON := map[string]any{}
	for name, def := range manifest.Schemas {
		schemaJSON[name] = def.JSON
	}

	paths := map[string]any{}
	for _, ep := range manifest.Endpoints {
		pathItem, _ := paths[ep.Path].(map[string]any)
		if pathItem == nil {
			pathItem = map[string]any{}
		}

		op := map[string]any{
			"operationId": ep.OperationID,
			"summary":     ep.Summary,
			"description": ep.Description,
			"tags":        []string{ep.Tag},
			"responses":   buildResponses(ep, manifest.Schemas),
		}

		if ep.Auth {
			op["security"] = []map[string][]string{
				{"bearerAuth": {}},
				{"apiKeyAuth": {}},
			}
		}

		params := buildParameters(ep)
		if len(params) > 0 {
			op["parameters"] = params
		}

		if ep.RequestSchema != "" {
			op["requestBody"] = map[string]any{
				"required": true,
				"content": map[string]any{
					"application/json": map[string]any{
						"schema": refSchema(ep.RequestSchema),
					},
				},
			}
		}

		if ep.Deprecated {
			op["deprecated"] = true
		}

		pathItem[strings.ToLower(ep.Method)] = op
		paths[ep.Path] = pathItem
	}

	doc := map[string]any{
		"openapi": "3.1.0",
		"info": map[string]any{
			"title":       "RateGuard API",
			"version":     "v1",
			"description": "Middleware-first control-plane API for RateGuard OSS.",
		},
		"servers": []any{
			map[string]any{"url": "http://localhost:8008", "description": "Local backend"},
		},
		"tags": []any{
			map[string]any{"name": "auth"},
			map[string]any{"name": "apis"},
			map[string]any{"name": "dashboard"},
			map[string]any{"name": "api-keys"},
			map[string]any{"name": "guardrails"},
			map[string]any{"name": "webhook"},
			map[string]any{"name": "proxy"},
			map[string]any{"name": "system"},
		},
		"paths": paths,
		"components": map[string]any{
			"schemas": schemaJSON,
			"securitySchemes": map[string]any{
				"bearerAuth": map[string]any{
					"type":         "http",
					"scheme":       "bearer",
					"bearerFormat": "JWT",
					"description":  "JWT access token in the Authorization header.",
				},
				"apiKeyAuth": map[string]any{
					"type":        "apiKey",
					"in":          "header",
					"name":        "X-API-Key",
					"description": "API key for machine clients.",
				},
			},
			"parameters": map[string]any{
				"IdempotencyKey": map[string]any{
					"name":        "Idempotency-Key",
					"in":          "header",
					"required":    true,
					"schema":      map[string]any{"type": "string"},
					"description": "Ensures write operations are safe to retry.",
				},
			},
		},
		"x-rateguard-event-envelope": map[string]any{
			"event_id":    "evt_123",
			"event_type":  "route.error_burst",
			"tenant_id":   "tnt_123",
			"route_id":    "rt_123",
			"upstream_id": "up_123",
			"trace_id":    "trace_123",
			"occurred_at": "2026-03-20T10:00:00Z",
			"payload":     map[string]any{},
		},
		"x-rateguard-realtime": map[string]any{
			"stream_endpoint":         "/api/v1/events/stream",
			"replay_endpoint":         "/api/v1/events/replay",
			"heartbeat_interval_secs": 15,
			"replay_since_format":     []string{"RFC3339Nano", "RFC3339", "unix-seconds", "unix-milliseconds"},
			"envelope_schema":         "#/components/schemas/RealtimeEventEnvelope",
			"transport":               "websocket,sse",
		},
	}

	return doc, nil
}

// JSON marshals the current document to canonical JSON.
func JSON() ([]byte, error) {
	doc, err := Build()
	if err != nil {
		return nil, err
	}
	return json.MarshalIndent(doc, "", "  ")
}

// GenerateTSClient renders the TypeScript SDK source from the same manifest.
func GenerateTSClient() (string, error) {
	manifest := manifest()

	var buf bytes.Buffer
	buf.WriteString("// Code generated by rateguard openapi generator. DO NOT EDIT.\n")
	buf.WriteString("/* eslint-disable @typescript-eslint/no-explicit-any */\n\n")
	buf.WriteString("export type JsonValue = string | number | boolean | null | JsonObject | JsonValue[];\n")
	buf.WriteString("export interface JsonObject { [key: string]: JsonValue; }\n")
	buf.WriteString("export interface RequestOptions { idempotencyKey?: string; headers?: HeadersInit; signal?: AbortSignal; }\n")
	buf.WriteString("export interface ClientConfig { baseUrl: string; accessToken?: string; apiKey?: string; fetchImpl?: typeof fetch; headers?: HeadersInit; }\n\n")

	names := make([]string, 0, len(manifest.Schemas))
	for name := range manifest.Schemas {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		buf.WriteString(manifest.Schemas[name].TS)
		if !strings.HasSuffix(manifest.Schemas[name].TS, "\n") {
			buf.WriteString("\n")
		}
		buf.WriteString("\n")
	}

	buf.WriteString("type RequestInput = {\n")
	buf.WriteString("  body?: unknown;\n")
	buf.WriteString("  params?: Record<string, string | number | boolean | undefined>;\n")
	buf.WriteString("  options?: RequestOptions;\n")
	buf.WriteString("};\n\n")

	buf.WriteString("function normalizeBaseUrl(baseUrl: string): string {\n")
	buf.WriteString("  return baseUrl.replace(/\\/$/, \"\");\n")
	buf.WriteString("}\n\n")

	buf.WriteString("function buildUrl(baseUrl: string, path: string, params?: Record<string, string | number | boolean | undefined>): string {\n")
	buf.WriteString("  let url = normalizeBaseUrl(baseUrl) + path;\n")
	buf.WriteString("  if (params) {\n")
	buf.WriteString("    for (const [key, value] of Object.entries(params)) {\n")
	buf.WriteString("      if (value === undefined || value === null) continue;\n")
	buf.WriteString("      const placeholder = `{${key}}`;\n")
	buf.WriteString("      if (url.includes(placeholder)) {\n")
	buf.WriteString("        url = url.split(placeholder).join(encodeURIComponent(String(value)));\n")
	buf.WriteString("      }\n")
	buf.WriteString("    }\n")
	buf.WriteString("    const query = new URLSearchParams();\n")
	buf.WriteString("    for (const [key, value] of Object.entries(params)) {\n")
	buf.WriteString("      if (value === undefined || value === null) continue;\n")
	buf.WriteString("      if (url.includes(`{${key}}`)) continue;\n")
	buf.WriteString("      query.set(key, String(value));\n")
	buf.WriteString("    }\n")
	buf.WriteString("    const queryString = query.toString();\n")
	buf.WriteString("    if (queryString) {\n")
	buf.WriteString("      url += url.includes(\"?\") ? `&${queryString}` : `?${queryString}`;\n")
	buf.WriteString("    }\n")
	buf.WriteString("  }\n")
	buf.WriteString("  return url;\n")
	buf.WriteString("}\n\n")

	buf.WriteString("function headerInit(value: HeadersInit | undefined): Headers {\n")
	buf.WriteString("  return new Headers(value ?? {});\n")
	buf.WriteString("}\n\n")

	buf.WriteString("export class RateGuardClient {\n")
	buf.WriteString("  constructor(private readonly config: ClientConfig) {}\n\n")
	buf.WriteString("  private async request<T>(method: string, path: string, input: RequestInput = {}): Promise<T> {\n")
	buf.WriteString("    const fetchImpl = this.config.fetchImpl ?? fetch;\n")
	buf.WriteString("    const url = buildUrl(this.config.baseUrl, path, input.params);\n")
	buf.WriteString("    const headers = headerInit(this.config.headers);\n")
	buf.WriteString("    if (this.config.accessToken) headers.set(\"Authorization\", `Bearer ${this.config.accessToken}`);\n")
	buf.WriteString("    if (this.config.apiKey) headers.set(\"X-API-Key\", this.config.apiKey);\n")
	buf.WriteString("    if (input.options?.idempotencyKey) headers.set(\"Idempotency-Key\", input.options.idempotencyKey);\n")
	buf.WriteString("    if (input.options?.headers) {\n")
	buf.WriteString("      for (const [key, value] of new Headers(input.options.headers).entries()) headers.set(key, value);\n")
	buf.WriteString("    }\n")
	buf.WriteString("    if (input.body !== undefined) headers.set(\"Content-Type\", \"application/json\");\n")
	buf.WriteString("    const response = await fetchImpl(url, {\n")
	buf.WriteString("      method,\n")
	buf.WriteString("      headers,\n")
	buf.WriteString("      body: input.body === undefined ? undefined : JSON.stringify(input.body),\n")
	buf.WriteString("      signal: input.options?.signal,\n")
	buf.WriteString("    });\n")
	buf.WriteString("    if (!response.ok) {\n")
	buf.WriteString("      throw new Error(`RateGuard request failed: ${response.status} ${response.statusText}`);\n")
	buf.WriteString("    }\n")
	buf.WriteString("    if (response.status === 204) return undefined as T;\n")
	buf.WriteString("    const contentType = response.headers.get(\"content-type\") ?? \"\";\n")
	buf.WriteString("    if (contentType.includes(\"application/json\")) return (await response.json()) as T;\n")
	buf.WriteString("    return (await response.text()) as unknown as T;\n")
	buf.WriteString("  }\n\n")

	for _, ep := range manifest.Endpoints {
		buf.WriteString(generateMethod(ep, manifest.Schemas))
		buf.WriteString("\n")
	}

	buf.WriteString("}\n\n")
	buf.WriteString("export function createClient(config: ClientConfig): RateGuardClient {\n")
	buf.WriteString("  return new RateGuardClient(config);\n")
	buf.WriteString("}\n\n")
	buf.WriteString("export function middleware(config: ClientConfig = { baseUrl: \"http://localhost:8008\" }) {\n")
	buf.WriteString("  const client = createClient(config);\n")
	buf.WriteString("  return (req: any, _res: any, next: any) => {\n")
	buf.WriteString("    req.rateguard = client;\n")
	buf.WriteString("    if (typeof next === \"function\") return next();\n")
	buf.WriteString("  };\n")
	buf.WriteString("}\n")

	return buf.String(), nil
}

// WriteArtifacts writes the generated OpenAPI JSON and TypeScript SDK to repo paths.
func WriteArtifacts(repoRoot string) error {
	docJSON, err := JSON()
	if err != nil {
		return err
	}
	ts, err := GenerateTSClient()
	if err != nil {
		return err
	}

	backendOpenAPI := filepath.Join(repoRoot, "apps", "gateway", "docs", "openapi.json")
	rootOpenAPI := filepath.Join(repoRoot, "packages", "openapi", "openapi.json")
	tsOut := filepath.Join(repoRoot, "packages", "sdk-ts", "generated", "rateguard.ts")

	if err := writeFile(backendOpenAPI, docJSON); err != nil {
		return err
	}
	if err := writeFile(rootOpenAPI, docJSON); err != nil {
		return err
	}
	if err := writeFile(tsOut, []byte(ts)); err != nil {
		return err
	}

	return nil
}

func buildResponses(ep EndpointDef, schemas map[string]SchemaDef) map[string]any {
	status := ep.SuccessStatus
	if status == "" {
		status = "200"
	}

	responses := map[string]any{
		status: map[string]any{
			"description": "Successful response",
		},
		"400": map[string]any{
			"description": "Bad request",
			"content": map[string]any{
				"application/json": map[string]any{"schema": refSchema("ErrorResponse")},
			},
		},
		"401": map[string]any{
			"description": "Unauthorized",
			"content": map[string]any{
				"application/json": map[string]any{"schema": refSchema("ErrorResponse")},
			},
		},
		"500": map[string]any{
			"description": "Internal server error",
			"content": map[string]any{
				"application/json": map[string]any{"schema": refSchema("ErrorResponse")},
			},
		},
	}

	if ep.OperationID == "streamEvents" {
		responses[status] = map[string]any{
			"description": "Server-Sent Event stream",
			"content": map[string]any{
				"text/event-stream": map[string]any{
					"schema": map[string]any{"type": "string"},
				},
			},
		}
		return responses
	}

	if ep.ResponseSchema != "" {
		responses[status] = map[string]any{
			"description": "Successful response",
			"content": map[string]any{
				"application/json": map[string]any{
					"schema": schemaRef(ep.ResponseSchema),
				},
			},
		}
	}

	return responses
}

func buildParameters(ep EndpointDef) []any {
	var params []any
	for _, p := range ep.Params {
		params = append(params, map[string]any{
			"name":        p.Name,
			"in":          p.In,
			"required":    p.Required,
			"description": p.Description,
			"schema": map[string]any{
				"type": p.Type,
			},
		})
	}
	if ep.Idempotency {
		params = append(params, map[string]any{
			"name":        "Idempotency-Key",
			"in":          "header",
			"required":    true,
			"schema":      map[string]any{"type": "string"},
			"description": "Ensures write operations are safe to retry.",
		})
	}
	return params
}

func schemaRef(name string) map[string]any {
	if strings.HasPrefix(name, "[]") {
		item := strings.TrimPrefix(name, "[]")
		return map[string]any{
			"type":  "array",
			"items": refSchema(item),
		}
	}
	return refSchema(name)
}

func refSchema(name string) map[string]any {
	return map[string]any{"$ref": "#/components/schemas/" + name}
}

func writeFile(path string, data []byte) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("create dir %s: %w", filepath.Dir(path), err)
	}
	if err := os.WriteFile(path, data, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}

func generateMethod(ep EndpointDef, schemas map[string]SchemaDef) string {
	respType := "void"
	if ep.ResponseSchema != "" {
		respType = tsTypeForSchema(ep.ResponseSchema, schemas)
	}

	var inputFields []string
	if ep.RequestSchema != "" {
		inputFields = append(inputFields, fmt.Sprintf("body: %s", tsTypeForSchema(ep.RequestSchema, schemas)))
	}
	if len(ep.Params) > 0 {
		paramParts := make([]string, 0, len(ep.Params))
		for _, p := range ep.Params {
			t := "string"
			switch p.Type {
			case "integer":
				t = "number"
			case "boolean":
				t = "boolean"
			}
			if !p.Required {
				t += " | undefined"
			}
			paramParts = append(paramParts, fmt.Sprintf("%s: %s", p.Name, t))
		}
		inputFields = append(inputFields, fmt.Sprintf("params: { %s }", strings.Join(paramParts, "; ")))
	}

	if len(inputFields) > 0 {
		inputFields = append(inputFields, "options?: RequestOptions")
	}

	signature := "input?: RequestOptions"
	if len(inputFields) > 0 {
		signature = fmt.Sprintf("input: { %s }", strings.Join(inputFields, "; "))
	} else if !ep.Auth && ep.RequestSchema == "" && len(ep.Params) == 0 {
		signature = "input?: { options?: RequestOptions }"
	}

	var callArgs []string
	if ep.RequestSchema != "" {
		callArgs = append(callArgs, "body: input.body")
	}
	if len(ep.Params) > 0 {
		callArgs = append(callArgs, "params: input.params")
	}
	switch {
	case len(inputFields) > 0:
		if ep.Idempotency {
			callArgs = append(callArgs, "options: { ...input.options }")
		} else {
			callArgs = append(callArgs, "options: input.options")
		}
	case !ep.Auth && ep.RequestSchema == "" && len(ep.Params) == 0:
		if ep.Idempotency {
			callArgs = append(callArgs, "options: { ...input?.options }")
		} else {
			callArgs = append(callArgs, "options: input?.options")
		}
	default:
		callArgs = append(callArgs, "options: input")
	}

	method := &strings.Builder{}
	method.WriteString(fmt.Sprintf("  async %s(%s): Promise<%s> {\n", ep.MethodName, signature, respType))
	method.WriteString("    return this.request<")
	method.WriteString(respType)
	method.WriteString(">(")
	method.WriteString(fmt.Sprintf("\"%s\", \"%s\"", strings.ToUpper(ep.Method), ep.Path))
	if len(callArgs) > 0 {
		method.WriteString(", {\n")
		for _, arg := range callArgs {
			method.WriteString("      ")
			method.WriteString(arg)
			method.WriteString(",\n")
		}
		method.WriteString("    }")
	}
	method.WriteString(");\n")
	method.WriteString("  }\n")
	return method.String()
}

func tsTypeForSchema(name string, schemas map[string]SchemaDef) string {
	if strings.HasPrefix(name, "[]") {
		return tsTypeForSchema(strings.TrimPrefix(name, "[]"), schemas) + "[]"
	}
	if def, ok := schemas[name]; ok {
		if strings.TrimSpace(def.TS) != "" {
			return name
		}
	}
	return "Record<string, unknown>"
}

func manifest() artifactSet {
	schemas := map[string]SchemaDef{
		"ErrorResponse": {
			JSON: map[string]any{
				"type": "object",
				"properties": map[string]any{
					"error":     map[string]any{"type": "string"},
					"message":   map[string]any{"type": "string"},
					"timestamp": map[string]any{"type": "string", "format": "date-time"},
				},
				"required":             []string{"error", "message", "timestamp"},
				"additionalProperties": true,
			},
			TS: "export interface ErrorResponse {\n  error: string;\n  message: string;\n  timestamp: string;\n  request_id?: string;\n  [key: string]: unknown;\n}\n",
		},
		"MessageResponse": {
			JSON: map[string]any{
				"type": "object",
				"properties": map[string]any{
					"message": map[string]any{"type": "string"},
				},
				"required":             []string{"message"},
				"additionalProperties": true,
			},
			TS: "export interface MessageResponse { message: string; [key: string]: unknown; }\n",
		},
		"HealthResponse": {
			JSON: map[string]any{"type": "object", "properties": map[string]any{"status": map[string]any{"type": "string"}, "service": map[string]any{"type": "string"}}, "required": []string{"status", "service"}},
			TS:   "export interface HealthResponse { status: string; service: string; [key: string]: unknown; }\n",
		},
		"User": {
			JSON: map[string]any{"type": "object", "properties": map[string]any{"id": map[string]any{"type": "string"}, "email": map[string]any{"type": "string"}, "handle": map[string]any{"type": "string"}, "preset": map[string]any{"type": "string"}, "active": map[string]any{"type": "boolean"}, "email_verified": map[string]any{"type": "boolean"}}, "additionalProperties": true},
			TS:   "export interface User { id: string; email: string; handle?: string; preset?: string; active?: boolean; email_verified?: boolean; [key: string]: unknown; }\n",
		},
		"AuthResponse": {
			JSON: map[string]any{"type": "object", "properties": map[string]any{"access_token": map[string]any{"type": "string"}, "refresh_token": map[string]any{"type": "string"}, "user": refSchema("User")}, "required": []string{"access_token", "user"}, "additionalProperties": true},
			TS:   "export interface AuthResponse { access_token: string; refresh_token?: string; user: User; [key: string]: unknown; }\n",
		},
		"CreateUserRequest": {
			JSON: map[string]any{"type": "object", "properties": map[string]any{"email": map[string]any{"type": "string"}, "password": map[string]any{"type": "string"}, "preset": map[string]any{"type": "string"}, "handle": map[string]any{"type": "string"}}, "required": []string{"email", "password"}, "additionalProperties": true},
			TS:   "export interface CreateUserRequest { email: string; password: string; preset?: string; handle?: string; [key: string]: unknown; }\n",
		},
		"HandleAvailabilityRequest": {
			JSON: map[string]any{"type": "object", "properties": map[string]any{"handle": map[string]any{"type": "string"}}, "required": []string{"handle"}, "additionalProperties": true},
			TS:   "export interface HandleAvailabilityRequest { handle: string; [key: string]: unknown; }\n",
		},
		"HandleAvailabilityResponse": {
			JSON: map[string]any{"type": "object", "properties": map[string]any{"available": map[string]any{"type": "boolean"}, "suggestions": map[string]any{"type": "array", "items": map[string]any{"type": "string"}}}, "required": []string{"available"}, "additionalProperties": true},
			TS:   "export interface HandleAvailabilityResponse { available: boolean; suggestions?: string[]; [key: string]: unknown; }\n",
		},
		"LoginRequest": {
			JSON: map[string]any{"type": "object", "properties": map[string]any{"email": map[string]any{"type": "string"}, "password": map[string]any{"type": "string"}}, "required": []string{"email", "password"}, "additionalProperties": true},
			TS:   "export interface LoginRequest { email: string; password: string; }\n",
		},
		"UpdateHandleRequest": {
			JSON: map[string]any{"type": "object", "properties": map[string]any{"handle": map[string]any{"type": "string"}}, "required": []string{"handle"}, "additionalProperties": true},
			TS:   "export interface UpdateHandleRequest { handle: string; [key: string]: unknown; }\n",
		},
		"HandleUpdateResponse": {
			JSON: map[string]any{"type": "object", "properties": map[string]any{"user": refSchema("User")}, "required": []string{"user"}, "additionalProperties": true},
			TS:   "export interface HandleUpdateResponse { user: User; [key: string]: unknown; }\n",
		},
		"ResetPasswordRequest": {
			JSON: map[string]any{"type": "object", "properties": map[string]any{"token": map[string]any{"type": "string"}, "password": map[string]any{"type": "string"}}, "required": []string{"token", "password"}, "additionalProperties": true},
			TS:   "export interface ResetPasswordRequest { token: string; password: string; }\n",
		},
		"APIConfig": {
			JSON: map[string]any{"type": "object", "properties": map[string]any{"id": map[string]any{"type": "string"}, "name": map[string]any{"type": "string"}, "upstream_url": map[string]any{"type": "string"}, "enabled": map[string]any{"type": "boolean"}, "rate_limit_per_second": map[string]any{"type": "integer"}, "burst_size": map[string]any{"type": "integer"}, "token_budget_per_hour": map[string]any{"type": "integer"}, "token_budget_mode": map[string]any{"type": "string"}}, "additionalProperties": true},
			TS:   "export interface APIConfig { id?: string; name?: string; upstream_url?: string; enabled?: boolean; rate_limit_per_second?: number; burst_size?: number; token_budget_per_hour?: number; token_budget_mode?: string; [key: string]: unknown; }\n",
		},
		"CreateAPIConfigRequest": {
			JSON: map[string]any{"type": "object", "properties": map[string]any{"name": map[string]any{"type": "string"}, "upstream_url": map[string]any{"type": "string"}, "enabled": map[string]any{"type": "boolean"}, "token_budget_per_hour": map[string]any{"type": "integer"}, "token_budget_mode": map[string]any{"type": "string"}}, "required": []string{"name", "upstream_url"}, "additionalProperties": true},
			TS:   "export interface CreateAPIConfigRequest { name: string; upstream_url: string; enabled?: boolean; token_budget_per_hour?: number; token_budget_mode?: string; [key: string]: unknown; }\n",
		},
		"UpdateAPIConfigRequest": {
			JSON: map[string]any{"type": "object", "properties": map[string]any{"name": map[string]any{"type": "string"}, "upstream_url": map[string]any{"type": "string"}, "enabled": map[string]any{"type": "boolean"}, "token_budget_per_hour": map[string]any{"type": "integer"}, "token_budget_mode": map[string]any{"type": "string"}}, "additionalProperties": true},
			TS:   "export interface UpdateAPIConfigRequest { name?: string; upstream_url?: string; enabled?: boolean; token_budget_per_hour?: number; token_budget_mode?: string; [key: string]: unknown; }\n",
		},
		"APIConfigListResponse": {
			JSON: map[string]any{"type": "object", "properties": map[string]any{"apis": map[string]any{"type": "array", "items": refSchema("APIConfig")}, "count": map[string]any{"type": "integer"}}, "additionalProperties": true},
			TS:   "export interface APIConfigListResponse { apis: APIConfig[]; count?: number; [key: string]: unknown; }\n",
		},
		"APIKey": {
			JSON: map[string]any{"type": "object", "properties": map[string]any{"id": map[string]any{"type": "string"}, "key_name": map[string]any{"type": "string"}, "last_used_at": map[string]any{"type": "string", "format": "date-time"}}, "additionalProperties": true},
			TS:   "export interface APIKey { id?: string; key_name?: string; last_used_at?: string; [key: string]: unknown; }\n",
		},
		"CreateAPIKeyRequest": {
			JSON: map[string]any{"type": "object", "properties": map[string]any{"key_name": map[string]any{"type": "string"}}, "required": []string{"key_name"}, "additionalProperties": true},
			TS:   "export interface CreateAPIKeyRequest { key_name: string; }\n",
		},
		"APIKeyListResponse": {
			JSON: map[string]any{"type": "object", "properties": map[string]any{"api_keys": map[string]any{"type": "array", "items": refSchema("APIKey")}, "count": map[string]any{"type": "integer"}}, "additionalProperties": true},
			TS:   "export interface APIKeyListResponse { api_keys: APIKey[]; count?: number; [key: string]: unknown; }\n",
		},
		"DashboardStats": {
			JSON: map[string]any{"type": "object", "properties": map[string]any{"requests_total": map[string]any{"type": "integer"}, "active_apis": map[string]any{"type": "integer"}, "active_connections": map[string]any{"type": "integer"}}, "additionalProperties": true},
			TS:   "export interface DashboardStats { requests_total?: number; active_apis?: number; active_connections?: number; [key: string]: unknown; }\n",
		},
		"UsageStats": {
			JSON: map[string]any{"type": "object", "properties": map[string]any{"requests_total": map[string]any{"type": "integer"}, "successful_requests": map[string]any{"type": "integer"}, "failed_requests": map[string]any{"type": "integer"}}, "additionalProperties": true},
			TS:   "export interface UsageStats { requests_total?: number; successful_requests?: number; failed_requests?: number; [key: string]: unknown; }\n",
		},
		"UsageHistoryResponse": {
			JSON: map[string]any{"type": "object", "properties": map[string]any{"points": map[string]any{"type": "array", "items": map[string]any{"type": "object", "additionalProperties": true}}}, "additionalProperties": true},
			TS:   "export interface UsageHistoryResponse { points?: Array<Record<string, unknown>>; [key: string]: unknown; }\n",
		},
		"RecentRequestsResponse": {
			JSON: map[string]any{"type": "object", "properties": map[string]any{"requests": map[string]any{"type": "array", "items": map[string]any{"type": "object", "additionalProperties": true}}}, "additionalProperties": true},
			TS:   "export interface RecentRequestsResponse { requests?: Array<Record<string, unknown>>; [key: string]: unknown; }\n",
		},
		"AlertsResponse": {
			JSON: map[string]any{"type": "object", "properties": map[string]any{"alerts": map[string]any{"type": "array", "items": map[string]any{"type": "object", "additionalProperties": true}}}, "additionalProperties": true},
			TS:   "export interface AlertsResponse { alerts?: Array<Record<string, unknown>>; [key: string]: unknown; }\n",
		},
		"CostEstimate": {
			JSON: map[string]any{"type": "object", "properties": map[string]any{"estimated_cost_cents": map[string]any{"type": "integer"}}, "additionalProperties": true},
			TS:   "export interface CostEstimate { estimated_cost_cents?: number; [key: string]: unknown; }\n",
		},
		"Settings": {
			JSON: map[string]any{"type": "object", "additionalProperties": true},
			TS:   "export interface Settings { [key: string]: unknown; }\n",
		},
		"OpenApiDocument": {
			JSON: map[string]any{"type": "object", "additionalProperties": true},
			TS:   "export interface OpenApiDocument { [key: string]: unknown; }\n",
		},
		"StreamingStats": {
			JSON: map[string]any{"type": "object", "additionalProperties": true},
			TS:   "export interface StreamingStats { [key: string]: unknown; }\n",
		},
		"StreamingHistoryResponse": {
			JSON: map[string]any{"type": "object", "additionalProperties": true},
			TS:   "export interface StreamingHistoryResponse { [key: string]: unknown; }\n",
		},
		"StreamingByApiResponse": {
			JSON: map[string]any{"type": "object", "additionalProperties": true},
			TS:   "export interface StreamingByApiResponse { [key: string]: unknown; }\n",
		},
		"QueueStats": {
			JSON: map[string]any{"type": "object", "additionalProperties": true},
			TS:   "export interface QueueStats { [key: string]: unknown; }\n",
		},
		"QueueConfig": {
			JSON: map[string]any{"type": "object", "additionalProperties": true},
			TS:   "export interface QueueConfig { [key: string]: unknown; }\n",
		},
		"TokenUsageSummary": {
			JSON: map[string]any{"type": "object", "additionalProperties": true},
			TS:   "export interface TokenUsageSummary { [key: string]: unknown; }\n",
		},
		"ModelPricing": {
			JSON: map[string]any{"type": "object", "properties": map[string]any{"provider": map[string]any{"type": "string"}, "model": map[string]any{"type": "string"}, "input_price_per_million": map[string]any{"type": "integer"}, "output_price_per_million": map[string]any{"type": "integer"}}, "additionalProperties": true},
			TS:   "export interface ModelPricing { provider?: string; model?: string; input_price_per_million?: number; output_price_per_million?: number; [key: string]: unknown; }\n",
		},
		"GuardrailConfig": {
			JSON: map[string]any{"type": "object", "additionalProperties": true},
			TS:   "export interface GuardrailConfig { [key: string]: unknown; }\n",
		},
		"CreateGuardrailConfigRequest": {
			JSON: map[string]any{"type": "object", "properties": map[string]any{"monthly_budget_cents": map[string]any{"type": "integer"}, "alert_threshold_pct": map[string]any{"type": "integer"}, "hard_limit_pct": map[string]any{"type": "integer"}, "notify_email": map[string]any{"type": "boolean"}, "notify_webhook": map[string]any{"type": "boolean"}, "webhook_url": map[string]any{"type": "string"}, "enabled": map[string]any{"type": "boolean"}}, "required": []string{"monthly_budget_cents", "alert_threshold_pct", "hard_limit_pct"}, "additionalProperties": true},
			TS:   "export interface CreateGuardrailConfigRequest { monthly_budget_cents: number; alert_threshold_pct: number; hard_limit_pct: number; notify_email?: boolean; notify_webhook?: boolean; webhook_url?: string; enabled?: boolean; [key: string]: unknown; }\n",
		},
		"GuardrailAlert": {
			JSON: map[string]any{"type": "object", "additionalProperties": true},
			TS:   "export interface GuardrailAlert { [key: string]: unknown; }\n",
		},
		"GuardrailOptimization": {
			JSON: map[string]any{"type": "object", "additionalProperties": true},
			TS:   "export interface GuardrailOptimization { [key: string]: unknown; }\n",
		},
		"WebhookStats": {
			JSON: map[string]any{"type": "object", "additionalProperties": true},
			TS:   "export interface WebhookStats { [key: string]: unknown; }\n",
		},
		"WebhookEvent": {
			JSON: map[string]any{"type": "object", "additionalProperties": true},
			TS:   "export interface WebhookEvent { [key: string]: unknown; }\n",
		},
		"RealtimeEventEnvelope": {
			JSON: map[string]any{
				"type": "object",
				"properties": map[string]any{
					"event_id":    map[string]any{"type": "string"},
					"event_type":  map[string]any{"type": "string"},
					"tenant_id":   map[string]any{"type": "string"},
					"route_id":    map[string]any{"type": "string"},
					"upstream_id": map[string]any{"type": "string"},
					"trace_id":    map[string]any{"type": "string"},
					"occurred_at": map[string]any{"type": "string", "format": "date-time"},
					"payload":     map[string]any{"type": "object", "additionalProperties": true},
				},
				"required":             []string{"event_id", "event_type", "occurred_at"},
				"additionalProperties": true,
			},
			TS: "export interface RealtimeEventEnvelope {\n  event_id: string;\n  event_type: string;\n  tenant_id?: string;\n  route_id?: string;\n  upstream_id?: string;\n  trace_id?: string;\n  occurred_at: string;\n  payload?: Record<string, unknown>;\n  [key: string]: unknown;\n}\n",
		},
		"RealtimeEventReplayResponse": {
			JSON: map[string]any{
				"type": "object",
				"properties": map[string]any{
					"since":  map[string]any{"type": "string"},
					"count":  map[string]any{"type": "integer"},
					"events": map[string]any{"type": "array", "items": refSchema("RealtimeEventEnvelope")},
				},
				"required":             []string{"count", "events"},
				"additionalProperties": true,
			},
			TS: "export interface RealtimeEventReplayResponse { since?: string; count: number; events: RealtimeEventEnvelope[]; [key: string]: unknown; }\n",
		},
		"RealtimeEventStreamResponse": {
			JSON: map[string]any{"type": "string"},
			TS:   "export type RealtimeEventStreamResponse = string;\n",
		},
		"WebhookConfig": {
			JSON: map[string]any{"type": "object", "additionalProperties": true},
			TS:   "export interface WebhookConfig { [key: string]: unknown; }\n",
		},
		"ProxyRequestPayload": {
			JSON: map[string]any{"type": "object", "additionalProperties": true},
			TS:   "export interface ProxyRequestPayload { [key: string]: unknown; }\n",
		},
		"ProxyResponse": {
			JSON: map[string]any{"type": "object", "additionalProperties": true},
			TS:   "export interface ProxyResponse { [key: string]: unknown; }\n",
		},
		"ProxyStats": {
			JSON: map[string]any{"type": "object", "additionalProperties": true},
			TS:   "export interface ProxyStats { [key: string]: unknown; }\n",
		},
		"CircuitBreakerStats": {
			JSON: map[string]any{"type": "object", "additionalProperties": true},
			TS:   "export interface CircuitBreakerStats { [key: string]: unknown; }\n",
		},
		"CircuitBreakerMetrics": {
			JSON: map[string]any{"type": "object", "additionalProperties": true},
			TS:   "export interface CircuitBreakerMetrics { [key: string]: unknown; }\n",
		},
		"AggregateRequest": {
			JSON: map[string]any{"type": "object", "additionalProperties": true},
			TS:   "export interface AggregateRequest { [key: string]: unknown; }\n",
		},
		"AggregateResponse": {
			JSON: map[string]any{"type": "object", "additionalProperties": true},
			TS:   "export interface AggregateResponse { [key: string]: unknown; }\n",
		},
		"RateLimitSuggestionResponse": {
			JSON: map[string]any{"type": "object", "additionalProperties": true},
			TS:   "export interface RateLimitSuggestionResponse { [key: string]: unknown; }\n",
		},
		"RateLimitObservationResponse": {
			JSON: map[string]any{"type": "object", "additionalProperties": true},
			TS:   "export interface RateLimitObservationResponse { [key: string]: unknown; }\n",
		},
		"RateLimitApplyResponse": {
			JSON: map[string]any{"type": "object", "additionalProperties": true},
			TS:   "export interface RateLimitApplyResponse { [key: string]: unknown; }\n",
		},
		"TestConnectionRequest": {
			JSON: map[string]any{"type": "object", "additionalProperties": true},
			TS:   "export interface TestConnectionRequest { [key: string]: unknown; }\n",
		},
		"TestConnectionResponse": {
			JSON: map[string]any{"type": "object", "additionalProperties": true},
			TS:   "export interface TestConnectionResponse { [key: string]: unknown; }\n",
		},
	}

	endpoints := []EndpointDef{
		{Method: "GET", Path: "/api/v1/openapi.json", OperationID: "getOpenApiJson", MethodName: "getOpenApiJson", Summary: "Get OpenAPI document", Description: "Return the live OpenAPI 3.1 document for RateGuard OSS.", Tag: "system", ResponseSchema: "OpenApiDocument", SuccessStatus: "200"},
		{Method: "POST", Path: "/api/v1/auth/signup", OperationID: "signUp", MethodName: "signUp", Summary: "Register a new user", Description: "Create a new user account with email and password.", Tag: "auth", RequestSchema: "CreateUserRequest", ResponseSchema: "AuthResponse", SuccessStatus: "201"},
		{Method: "POST", Path: "/api/v1/auth/handle/check", OperationID: "checkHandleAvailability", MethodName: "checkHandleAvailability", Summary: "Check handle availability", Description: "Check whether a handle can be claimed.", Tag: "auth", RequestSchema: "HandleAvailabilityRequest", ResponseSchema: "HandleAvailabilityResponse", SuccessStatus: "200"},
		{Method: "POST", Path: "/api/v1/auth/login", OperationID: "login", MethodName: "login", Summary: "Log in", Description: "Authenticate a user and return JWT tokens.", Tag: "auth", RequestSchema: "LoginRequest", ResponseSchema: "AuthResponse", SuccessStatus: "200"},
		{Method: "POST", Path: "/api/v1/auth/refresh", OperationID: "refreshToken", MethodName: "refreshToken", Summary: "Refresh tokens", Description: "Refresh an access token using a refresh token.", Tag: "auth", ResponseSchema: "AuthResponse", SuccessStatus: "200"},
		{Method: "POST", Path: "/api/v1/auth/logout", OperationID: "logout", MethodName: "logout", Summary: "Log out", Description: "Invalidate the current session.", Tag: "auth", ResponseSchema: "MessageResponse", SuccessStatus: "200"},
		{Method: "GET", Path: "/api/v1/auth/me", OperationID: "getMe", MethodName: "getMe", Summary: "Get current user", Description: "Return the current authenticated user.", Tag: "auth", Auth: true, ResponseSchema: "User", SuccessStatus: "200"},
		{Method: "PUT", Path: "/api/v1/auth/handle", OperationID: "updateHandle", MethodName: "updateHandle", Summary: "Update handle", Description: "Update the current user's handle.", Tag: "auth", Auth: true, RequestSchema: "UpdateHandleRequest", ResponseSchema: "HandleUpdateResponse", SuccessStatus: "200"},
		{Method: "POST", Path: "/api/v1/auth/request-reset", OperationID: "requestPasswordReset", MethodName: "requestPasswordReset", Summary: "Request password reset", Description: "Send a password reset link to the user email.", Tag: "auth", RequestSchema: "LoginRequest", ResponseSchema: "MessageResponse", SuccessStatus: "200"},
		{Method: "POST", Path: "/api/v1/auth/reset-password", OperationID: "resetPassword", MethodName: "resetPassword", Summary: "Reset password", Description: "Reset a password using a reset token.", Tag: "auth", RequestSchema: "ResetPasswordRequest", ResponseSchema: "MessageResponse", SuccessStatus: "200"},
		{Method: "GET", Path: "/api/v1/auth/verify", OperationID: "verifyEmail", MethodName: "verifyEmail", Summary: "Verify email", Description: "Verify a user's email using a token.", Tag: "auth", Params: []ParamDef{{Name: "token", In: "query", Required: true, Type: "string", Description: "Verification token"}}, ResponseSchema: "MessageResponse", SuccessStatus: "200"},
		{Method: "POST", Path: "/api/v1/auth/resend-verification", OperationID: "resendVerificationEmail", MethodName: "resendVerificationEmail", Summary: "Resend verification", Description: "Resend the verification email to the user.", Tag: "auth", ResponseSchema: "MessageResponse", SuccessStatus: "200"},
		{Method: "GET", Path: "/api/v1/auth/geo", OperationID: "detectGeo", MethodName: "detectGeo", Summary: "Detect geo", Description: "Infer country and currency from the request IP.", Tag: "auth", ResponseSchema: "MessageResponse", SuccessStatus: "200"},
		{Method: "GET", Path: "/api/v1/apis", OperationID: "listApiConfigs", MethodName: "listApiConfigs", Summary: "List API configs", Description: "Return the current API configurations.", Tag: "apis", Auth: true, ResponseSchema: "APIConfigListResponse", SuccessStatus: "200"},
		{Method: "POST", Path: "/api/v1/apis", OperationID: "createApiConfig", MethodName: "createApiConfig", Summary: "Create API config", Description: "Create a new API configuration.", Tag: "apis", Auth: true, Idempotency: true, RequestSchema: "CreateAPIConfigRequest", ResponseSchema: "APIConfig", SuccessStatus: "201"},
		{Method: "GET", Path: "/api/v1/apis/{id}", OperationID: "getApiConfig", MethodName: "getApiConfig", Summary: "Get API config", Description: "Retrieve a specific API configuration.", Tag: "apis", Auth: true, Params: []ParamDef{{Name: "id", In: "path", Required: true, Type: "string", Description: "API config ID"}}, ResponseSchema: "APIConfig", SuccessStatus: "200"},
		{Method: "PUT", Path: "/api/v1/apis/{id}", OperationID: "updateApiConfig", MethodName: "updateApiConfig", Summary: "Update API config", Description: "Update an existing API configuration.", Tag: "apis", Auth: true, Idempotency: true, Params: []ParamDef{{Name: "id", In: "path", Required: true, Type: "string", Description: "API config ID"}}, RequestSchema: "UpdateAPIConfigRequest", ResponseSchema: "APIConfig", SuccessStatus: "200"},
		{Method: "DELETE", Path: "/api/v1/apis/{id}", OperationID: "deleteApiConfig", MethodName: "deleteApiConfig", Summary: "Delete API config", Description: "Delete an API configuration.", Tag: "apis", Auth: true, Idempotency: true, Params: []ParamDef{{Name: "id", In: "path", Required: true, Type: "string", Description: "API config ID"}}, ResponseSchema: "MessageResponse", SuccessStatus: "200"},
		{Method: "POST", Path: "/api/v1/apis/test-connection", OperationID: "testConnection", MethodName: "testConnection", Summary: "Test API connection", Description: "Validate an upstream connection for a configuration.", Tag: "apis", Auth: true, Idempotency: true, RequestSchema: "TestConnectionRequest", ResponseSchema: "TestConnectionResponse", SuccessStatus: "200"},
		{Method: "GET", Path: "/api/v1/apis/{id}/rate-limit/suggestions", OperationID: "getRateLimitSuggestions", MethodName: "getRateLimitSuggestions", Summary: "Rate limit suggestions", Description: "Return rate limit suggestions for an API.", Tag: "apis", Auth: true, Params: []ParamDef{{Name: "id", In: "path", Required: true, Type: "string", Description: "API config ID"}}, ResponseSchema: "RateLimitSuggestionResponse", SuccessStatus: "200"},
		{Method: "GET", Path: "/api/v1/apis/{id}/rate-limit/observations", OperationID: "getRateLimitObservations", MethodName: "getRateLimitObservations", Summary: "Rate limit observations", Description: "Return observed rate-limit data for an API.", Tag: "apis", Auth: true, Params: []ParamDef{{Name: "id", In: "path", Required: true, Type: "string", Description: "API config ID"}}, ResponseSchema: "RateLimitObservationResponse", SuccessStatus: "200"},
		{Method: "POST", Path: "/api/v1/apis/{id}/rate-limit/apply", OperationID: "applyRateLimitSuggestion", MethodName: "applyRateLimitSuggestion", Summary: "Apply rate limit suggestion", Description: "Apply a suggested policy to an API.", Tag: "apis", Auth: true, Idempotency: true, Params: []ParamDef{{Name: "id", In: "path", Required: true, Type: "string", Description: "API config ID"}}, ResponseSchema: "RateLimitApplyResponse", SuccessStatus: "200"},
		{Method: "GET", Path: "/api/v1/api-keys", OperationID: "listApiKeys", MethodName: "listApiKeys", Summary: "List API keys", Description: "List API keys for the authenticated user.", Tag: "api-keys", Auth: true, ResponseSchema: "APIKeyListResponse", SuccessStatus: "200"},
		{Method: "POST", Path: "/api/v1/api-keys", OperationID: "createApiKey", MethodName: "createApiKey", Summary: "Create API key", Description: "Create a new API key.", Tag: "api-keys", Auth: true, Idempotency: true, RequestSchema: "CreateAPIKeyRequest", ResponseSchema: "APIKey", SuccessStatus: "201"},
		{Method: "DELETE", Path: "/api/v1/api-keys/{id}", OperationID: "revokeApiKey", MethodName: "revokeApiKey", Summary: "Revoke API key", Description: "Revoke an API key.", Tag: "api-keys", Auth: true, Idempotency: true, Params: []ParamDef{{Name: "id", In: "path", Required: true, Type: "string", Description: "API key ID"}}, ResponseSchema: "MessageResponse", SuccessStatus: "200"},
		{Method: "GET", Path: "/api/v1/dashboard/stats", OperationID: "getDashboardStats", MethodName: "getDashboardStats", Summary: "Get dashboard stats", Description: "Return the dashboard summary metrics.", Tag: "dashboard", Auth: true, ResponseSchema: "DashboardStats", SuccessStatus: "200"},
		{Method: "GET", Path: "/api/v1/dashboard/usage", OperationID: "getUsageStats", MethodName: "getUsageStats", Summary: "Get usage stats", Description: "Return usage statistics for the current user.", Tag: "dashboard", Auth: true, ResponseSchema: "UsageStats", SuccessStatus: "200"},
		{Method: "GET", Path: "/api/v1/dashboard/usage/history", OperationID: "getUsageHistory", MethodName: "getUsageHistory", Summary: "Get usage history", Description: "Return usage history data.", Tag: "dashboard", Auth: true, Params: []ParamDef{{Name: "period", In: "query", Required: false, Type: "string", Description: "Aggregation period"}}, ResponseSchema: "UsageHistoryResponse", SuccessStatus: "200"},
		{Method: "GET", Path: "/api/v1/dashboard/requests/recent", OperationID: "getRecentRequests", MethodName: "getRecentRequests", Summary: "Get recent requests", Description: "Return recent requests for the dashboard.", Tag: "dashboard", Auth: true, ResponseSchema: "RecentRequestsResponse", SuccessStatus: "200"},
		{Method: "GET", Path: "/api/v1/dashboard/alerts", OperationID: "getAlerts", MethodName: "getAlerts", Summary: "Get dashboard alerts", Description: "Return dashboard alerts.", Tag: "dashboard", Auth: true, ResponseSchema: "AlertsResponse", SuccessStatus: "200"},
		{Method: "GET", Path: "/api/v1/dashboard/costs", OperationID: "getCostEstimate", MethodName: "getCostEstimate", Summary: "Get cost estimate", Description: "Return cost estimates for the current workspace.", Tag: "dashboard", Auth: true, ResponseSchema: "CostEstimate", SuccessStatus: "200"},
		{Method: "GET", Path: "/api/v1/dashboard/settings", OperationID: "getSettings", MethodName: "getSettings", Summary: "Get settings", Description: "Return dashboard settings.", Tag: "dashboard", Auth: true, ResponseSchema: "Settings", SuccessStatus: "200"},
		{Method: "PUT", Path: "/api/v1/dashboard/settings", OperationID: "updateSettings", MethodName: "updateSettings", Summary: "Update settings", Description: "Update dashboard settings.", Tag: "dashboard", Auth: true, Idempotency: true, RequestSchema: "Settings", ResponseSchema: "Settings", SuccessStatus: "200"},
		{Method: "POST", Path: "/api/v1/dashboard/settings/password", OperationID: "changePassword", MethodName: "changePassword", Summary: "Change password", Description: "Change the current user's password.", Tag: "dashboard", Auth: true, Idempotency: true, RequestSchema: "ResetPasswordRequest", ResponseSchema: "MessageResponse", SuccessStatus: "200"},
		{Method: "GET", Path: "/api/v1/dashboard/stats/streaming", OperationID: "getStreamingStats", MethodName: "getStreamingStats", Summary: "Get streaming stats", Description: "Return streaming analytics stats.", Tag: "dashboard", Auth: true, ResponseSchema: "StreamingStats", SuccessStatus: "200"},
		{Method: "GET", Path: "/api/v1/dashboard/streaming/history", OperationID: "getStreamingHistory", MethodName: "getStreamingHistory", Summary: "Get streaming history", Description: "Return streaming analytics history.", Tag: "dashboard", Auth: true, Params: []ParamDef{{Name: "period", In: "query", Required: false, Type: "string", Description: "Aggregation period"}}, ResponseSchema: "StreamingHistoryResponse", SuccessStatus: "200"},
		{Method: "GET", Path: "/api/v1/dashboard/streaming/by-api", OperationID: "getStreamingByApi", MethodName: "getStreamingByApi", Summary: "Get streaming by API", Description: "Return streaming analytics grouped by API.", Tag: "dashboard", Auth: true, Params: []ParamDef{{Name: "period", In: "query", Required: false, Type: "string", Description: "Aggregation period"}, {Name: "api_id", In: "query", Required: false, Type: "string", Description: "API ID filter"}}, ResponseSchema: "StreamingByApiResponse", SuccessStatus: "200"},
		{Method: "GET", Path: "/api/v1/dashboard/queues", OperationID: "getQueues", MethodName: "getQueues", Summary: "Get queues", Description: "Return queue statistics.", Tag: "dashboard", Auth: true, ResponseSchema: "QueueStats", SuccessStatus: "200"},
		{Method: "GET", Path: "/api/v1/dashboard/queues/active", OperationID: "getActiveQueues", MethodName: "getActiveQueues", Summary: "Get active queues", Description: "Return active queue items.", Tag: "dashboard", Auth: true, ResponseSchema: "QueueStats", SuccessStatus: "200"},
		{Method: "GET", Path: "/api/v1/dashboard/queues/config", OperationID: "getQueueConfig", MethodName: "getQueueConfig", Summary: "Get queue config", Description: "Return queue configuration.", Tag: "dashboard", Auth: true, ResponseSchema: "QueueConfig", SuccessStatus: "200"},
		{Method: "PUT", Path: "/api/v1/dashboard/queues/config", OperationID: "updateQueueConfig", MethodName: "updateQueueConfig", Summary: "Update queue config", Description: "Update queue configuration.", Tag: "dashboard", Auth: true, Idempotency: true, RequestSchema: "QueueConfig", ResponseSchema: "QueueConfig", SuccessStatus: "200"},
		{Method: "DELETE", Path: "/api/v1/dashboard/queues/{request_id}", OperationID: "cancelQueuedRequest", MethodName: "cancelQueuedRequest", Summary: "Cancel queued request", Description: "Cancel a queued request by ID.", Tag: "dashboard", Auth: true, Idempotency: true, Params: []ParamDef{{Name: "request_id", In: "path", Required: true, Type: "string", Description: "Queued request ID"}}, ResponseSchema: "MessageResponse", SuccessStatus: "200"},
		{Method: "POST", Path: "/api/v1/dashboard/api-key/regenerate", OperationID: "regenerateApiKey", MethodName: "regenerateApiKey", Summary: "Regenerate API key", Description: "Regenerate the dashboard API key.", Tag: "dashboard", Auth: true, Idempotency: true, ResponseSchema: "APIKey", SuccessStatus: "200"},
		{Method: "GET", Path: "/api/v1/dashboard/tokens", OperationID: "getTokenUsage", MethodName: "getTokenUsage", Summary: "Get token usage", Description: "Return token usage summary for LLM models.", Tag: "dashboard", Auth: true, ResponseSchema: "TokenUsageSummary", SuccessStatus: "200"},
		{Method: "GET", Path: "/api/v1/models/pricing", OperationID: "getModelPricing", MethodName: "getModelPricing", Summary: "Get model pricing", Description: "Return pricing for supported LLM models.", Tag: "dashboard", Auth: true, ResponseSchema: "[]ModelPricing", SuccessStatus: "200"},
		{Method: "GET", Path: "/api/v1/guardrails/config", OperationID: "getGuardrailConfig", MethodName: "getGuardrailConfig", Summary: "Get cost guardrails", Description: "Return the current cost guardrail config.", Tag: "guardrails", Auth: true, ResponseSchema: "GuardrailConfig", SuccessStatus: "200"},
		{Method: "POST", Path: "/api/v1/guardrails/config", OperationID: "updateGuardrailConfig", MethodName: "updateGuardrailConfig", Summary: "Update cost guardrails", Description: "Create or update cost guardrails.", Tag: "guardrails", Auth: true, Idempotency: true, RequestSchema: "CreateGuardrailConfigRequest", ResponseSchema: "GuardrailConfig", SuccessStatus: "200"},
		{Method: "DELETE", Path: "/api/v1/guardrails/config", OperationID: "deleteGuardrailConfig", MethodName: "deleteGuardrailConfig", Summary: "Delete cost guardrails", Description: "Disable cost guardrails.", Tag: "guardrails", Auth: true, Idempotency: true, ResponseSchema: "MessageResponse", SuccessStatus: "200"},
		{Method: "GET", Path: "/api/v1/guardrails/alerts", OperationID: "getGuardrailAlerts", MethodName: "getGuardrailAlerts", Summary: "Get guardrail alerts", Description: "Return cost guardrail alerts.", Tag: "guardrails", Auth: true, ResponseSchema: "AlertsResponse", SuccessStatus: "200"},
		{Method: "POST", Path: "/api/v1/guardrails/alerts/{id}/ack", OperationID: "acknowledgeGuardrailAlert", MethodName: "acknowledgeGuardrailAlert", Summary: "Acknowledge alert", Description: "Acknowledge a guardrail alert.", Tag: "guardrails", Auth: true, Idempotency: true, Params: []ParamDef{{Name: "id", In: "path", Required: true, Type: "string", Description: "Alert ID"}}, ResponseSchema: "MessageResponse", SuccessStatus: "200"},
		{Method: "GET", Path: "/api/v1/guardrails/optimizations", OperationID: "getGuardrailOptimizations", MethodName: "getGuardrailOptimizations", Summary: "Get guardrail optimizations", Description: "Return cost optimization suggestions.", Tag: "guardrails", Auth: true, ResponseSchema: "GuardrailOptimization", SuccessStatus: "200"},
		{Method: "POST", Path: "/api/v1/webhook/inbox", OperationID: "handleWebhookInbox", MethodName: "handleWebhookInbox", Summary: "Handle webhook inbox", Description: "Accept an inbound webhook payload.", Tag: "webhook", Auth: true, Idempotency: true, ResponseSchema: "WebhookEvent", SuccessStatus: "200"},
		{Method: "GET", Path: "/api/v1/webhook/status", OperationID: "getWebhookStatus", MethodName: "getWebhookStatus", Summary: "Get webhook status", Description: "Return webhook relay status.", Tag: "webhook", Auth: true, ResponseSchema: "MessageResponse", SuccessStatus: "200"},
		{Method: "GET", Path: "/api/v1/webhook/stats", OperationID: "getWebhookStats", MethodName: "getWebhookStats", Summary: "Get webhook stats", Description: "Return webhook delivery statistics.", Tag: "webhook", Auth: true, ResponseSchema: "WebhookStats", SuccessStatus: "200"},
		{Method: "GET", Path: "/api/v1/webhook/events/{id}", OperationID: "getWebhookEvent", MethodName: "getWebhookEvent", Summary: "Get webhook event", Description: "Return a single webhook event.", Tag: "webhook", Auth: true, Params: []ParamDef{{Name: "id", In: "path", Required: true, Type: "string", Description: "Webhook event ID"}}, ResponseSchema: "WebhookEvent", SuccessStatus: "200"},
		{Method: "POST", Path: "/api/v1/webhook/events/{id}/replay", OperationID: "replayWebhookEvent", MethodName: "replayWebhookEvent", Summary: "Replay webhook event", Description: "Replay a webhook event.", Tag: "webhook", Auth: true, Idempotency: true, Params: []ParamDef{{Name: "id", In: "path", Required: true, Type: "string", Description: "Webhook event ID"}}, ResponseSchema: "MessageResponse", SuccessStatus: "200"},
		{Method: "GET", Path: "/api/v1/events/replay", OperationID: "replayEvents", MethodName: "replayEvents", Summary: "Replay realtime events", Description: "Return a replay window of normalized realtime events for catch-up after a disconnect.", Tag: "system", Auth: true, Params: []ParamDef{{Name: "since", In: "query", Required: false, Type: "string", Description: "Replay start timestamp in RFC3339 or Unix seconds/milliseconds"}, {Name: "limit", In: "query", Required: false, Type: "integer", Description: "Maximum number of events to return"}}, ResponseSchema: "RealtimeEventReplayResponse", SuccessStatus: "200"},
		{Method: "GET", Path: "/api/v1/events/stream", OperationID: "streamEvents", MethodName: "streamEvents", Summary: "Stream realtime events", Description: "Open a Server-Sent Events stream for live realtime updates. Use EventSource or another SSE client to consume the response body.", Tag: "system", Auth: true, ResponseSchema: "RealtimeEventStreamResponse", SuccessStatus: "200"},
		{Method: "POST", Path: "/api/v1/proxy", OperationID: "proxyRequest", MethodName: "proxyRequest", Summary: "Proxy request", Description: "Execute a proxy request with policy enforcement.", Tag: "proxy", Auth: true, Idempotency: true, RequestSchema: "ProxyRequestPayload", ResponseSchema: "ProxyResponse", SuccessStatus: "200"},
		{Method: "GET", Path: "/api/v1/proxy/stats", OperationID: "getProxyStats", MethodName: "getProxyStats", Summary: "Get proxy stats", Description: "Return proxy statistics.", Tag: "proxy", Auth: true, ResponseSchema: "ProxyStats", SuccessStatus: "200"},
		{Method: "GET", Path: "/api/v1/proxy/circuit-breakers/stats", OperationID: "getCircuitBreakerStats", MethodName: "getCircuitBreakerStats", Summary: "Get circuit breaker stats", Description: "Return circuit breaker statistics.", Tag: "proxy", Auth: true, ResponseSchema: "CircuitBreakerStats", SuccessStatus: "200"},
		{Method: "GET", Path: "/api/v1/proxy/circuit-breakers/metrics", OperationID: "getCircuitBreakerMetrics", MethodName: "getCircuitBreakerMetrics", Summary: "Get circuit breaker metrics", Description: "Return circuit breaker metrics.", Tag: "proxy", Auth: true, ResponseSchema: "CircuitBreakerMetrics", SuccessStatus: "200"},
		{Method: "POST", Path: "/api/v1/proxy/circuit-breakers/{api_id}/reset", OperationID: "resetCircuitBreaker", MethodName: "resetCircuitBreaker", Summary: "Reset circuit breaker", Description: "Reset a circuit breaker for one API.", Tag: "proxy", Auth: true, Idempotency: true, Params: []ParamDef{{Name: "api_id", In: "path", Required: true, Type: "string", Description: "API ID"}}, ResponseSchema: "MessageResponse", SuccessStatus: "200"},
		{Method: "POST", Path: "/api/v1/aggregate", OperationID: "aggregate", MethodName: "aggregate", Summary: "Aggregate requests", Description: "Aggregate requests into a summary response.", Tag: "system", Idempotency: true, RequestSchema: "AggregateRequest", ResponseSchema: "AggregateResponse", SuccessStatus: "200"},
		{Method: "GET", Path: "/api/v1/stats", OperationID: "getStats", MethodName: "getStats", Summary: "Get stats", Description: "Return aggregate stats.", Tag: "system", ResponseSchema: "DashboardStats", SuccessStatus: "200"},
		{Method: "POST", Path: "/api/v1/stats/reset", OperationID: "resetStats", MethodName: "resetStats", Summary: "Reset stats", Description: "Reset stats counters.", Tag: "system", Idempotency: true, ResponseSchema: "MessageResponse", SuccessStatus: "200"},
	}

	return artifactSet{Schemas: schemas, Endpoints: endpoints}
}

func writeGeneratedArtifacts(repoRoot string) error {
	return WriteArtifacts(repoRoot)
}
