"""Static embedder: loader, tokenizer pipeline, pooling math, and the
gated golden-conformance test against the real converted model."""

from __future__ import annotations

import io
import json
import math
import os
import struct
from pathlib import Path

import pytest

from rateguard import StaticEmbedder

GOLDENS = Path(__file__).resolve().parents[3] / "conformance" / "static_embedding_vectors.json"


def build_mini_rgemb(
    vocab: list[str],
    dim: int,
    rows: list[list[float]],
    *,
    normalize: bool = True,
) -> bytes:
    header = {
        "format": "rgemb/1",
        "source": "mini-test",
        "dim": dim,
        "vocab_size": len(vocab),
        "dtype": "f32",
        "normalize": normalize,
        "norm_epsilon": 1e-32,
        "drop_token_ids": [1],
        "tokenizer": {
            "type": "wordpiece",
            "lowercase": True,
            "strip_accents": True,
            "clean_text": True,
            "handle_chinese_chars": True,
            "continuing_subword_prefix": "##",
            "unk_id": 1,
            "max_input_chars_per_word": 10,
        },
    }
    hb = json.dumps(header).encode()
    buf = io.BytesIO()
    buf.write(b"RGEMBED1")
    buf.write(struct.pack("<I", len(hb)))
    buf.write(hb)
    for tok in vocab:
        b = tok.encode()
        buf.write(struct.pack("<H", len(b)))
        buf.write(b)
    for row in rows:
        assert len(row) == dim
        buf.write(struct.pack(f"<{dim}f", *row))
    return buf.getvalue()


def mini_embedder() -> StaticEmbedder:
    vocab = ["[PAD]", "[UNK]", "hello", "world", "##ld", "wor", "cafe", "!"]
    rows = [
        [0, 0], [9, 9], [1, 0], [0, 1], [0.5, 0.5], [2, 0], [0, 2], [1, 1],
    ]
    return StaticEmbedder.read(io.BytesIO(build_mini_rgemb(vocab, 2, [[float(x) for x in r] for r in rows])))


@pytest.mark.parametrize(
    ("text", "want"),
    [
        ("HELLO World", [2, 3]),
        ("hello!world", [2, 7, 3]),
        ("world hello", [3, 2]),
        ("worldx", [1]),  # wor+##ld+x: x unmatched → whole word UNK
        ("café", [6]),
        ("zzz", [1]),
        ("hellohellohello", [1]),  # 15 > 10 cap
        ("he\x00llo", [2]),
        ("  hello\t\nworld  ", [2, 3]),
        ("", []),
    ],
)
def test_tokenize_pipeline(text: str, want: list[int]) -> None:
    assert mini_embedder().tokenize(text) == want


def test_pooling_math() -> None:
    e = mini_embedder()
    # "hello world" → rows (1,0),(0,1) → mean (0.5,0.5) → normalized (√2/2, √2/2).
    v = e.embed_sync("hello world")
    for x in v:
        assert abs(x - math.sqrt(2) / 2) < 1e-6
    # Unknown-only and empty text: zero vector.
    assert e.embed_sync("zzz qqq") == [0.0, 0.0]
    assert e.embed_sync("") == [0.0, 0.0]


@pytest.mark.asyncio
async def test_async_embed_matches_sync() -> None:
    e = mini_embedder()
    assert await e.embed("hello world") == e.embed_sync("hello world")


def test_rejects_garbage() -> None:
    with pytest.raises(ValueError):
        StaticEmbedder.read(io.BytesIO(b"not a model"))
    with pytest.raises(ValueError):
        StaticEmbedder.read(io.BytesIO(b"RGEMBED1" + b"\xff\xff\xff\xff"))


def test_golden_conformance() -> None:
    """Gated: RATEGUARD_EMBED_MODEL=/path/to/potion-base-2M.rgemb pytest.

    Goldens were generated by the reference model2vec library itself.
    model2vec's tokenize() removes unknown-token ids, so golden token_ids
    are post-drop; we filter ours the same way before comparing.
    """
    model_path = os.environ.get("RATEGUARD_EMBED_MODEL")
    if not model_path:
        pytest.skip("RATEGUARD_EMBED_MODEL not set (see scripts/convert_model2vec.py)")
    e = StaticEmbedder.load(model_path)
    goldens = json.loads(GOLDENS.read_text())
    assert e.dim == goldens["dim"]

    drop = frozenset(e._drop)  # noqa: SLF001 — asserting internal drop behavior deliberately
    for case in goldens["cases"]:
        got_ids = [i for i in e.tokenize(case["text"]) if i not in drop]
        assert got_ids == case["token_ids"], f"token ids diverge for {case['text']!r}"
        vec = e.embed_sync(case["text"])
        for j, (got, want) in enumerate(zip(vec, case["embedding"], strict=True)):
            assert abs(got - want) <= 1e-4, f"{case['text']!r} dim {j}: {got} vs {want}"
