"""Replays the same admission sequence used by the Go and Node SDKs against
the shared oracle in conformance/token_bucket_vectors.json. A failure here
means Python has drifted from the documented cross-language behavior — not
just from its own past test suite.
"""

from __future__ import annotations

import base64
import json

import pytest
from datetime import datetime, timezone
from pathlib import Path

from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey

from rateguard import (
    GENESIS_PREV_HASH,
    BudgetGrant,
    EvidenceChain,
    RateLimiter,
    ShardedLimiter,
    SpendReceiptClaims,
    issue_spend_receipt,
    signing_payload,
)
from rateguard.core.budget_attestation import private_key_from_raw
from rateguard.core.outbound import _extract_sse_usage
from rateguard.types import RateLimitOptions

from .helpers import FixedClock

VECTORS_PATH = Path(__file__).resolve().parents[3] / "conformance" / "token_bucket_vectors.json"
EXPIRY_VECTORS_PATH = (
    Path(__file__).resolve().parents[3] / "conformance" / "budget_attestation_expiry_vectors.json"
)


def test_matches_shared_oracle() -> None:
    vectors = json.loads(VECTORS_PATH.read_text())

    clock = FixedClock()
    limiter = RateLimiter(clock, capacity=1_000)
    options = RateLimitOptions(
        requests_per_second=vectors["policy"]["requests_per_second"],
        burst=vectors["policy"]["burst"],
    )

    for i, step in enumerate(vectors["steps"]):
        clock.advance(step["advance_ms"])
        d = limiter.increment("conformance-key", options, float(step["n"]))
        assert d.allowed == step["allowed"], f"step {i} ({step['note']})"
        if step["allowed"]:
            assert d.remaining == step["remaining"], f"step {i} ({step['note']})"
        else:
            assert d.retry_after_ms == step["retry_after_ms"], f"step {i} ({step['note']})"


def test_budget_attestation_expiry_matches_shared_oracle() -> None:
    """Replays conformance/budget_attestation_expiry_vectors.json against
    signing_payload, proving Python formats expires_at identically to Go and
    Node inside the Ed25519 signing payload — not just that Python's own
    round-trip tests pass. A failure here means a cross-language attested
    budget token would fail to verify."""
    vectors = json.loads(EXPIRY_VECTORS_PATH.read_text())
    delegate_public_key = Ed25519PrivateKey.generate().public_key()

    for i, case in enumerate(vectors["cases"]):
        expires_at = datetime.fromtimestamp(case["epoch_ms"] / 1000, tz=timezone.utc)
        grant = BudgetGrant(max_tokens=100, max_depth=1, expires_at=expires_at)
        raw = signing_payload(grant, delegate_public_key)
        decoded = json.loads(raw)
        assert decoded["expires_at"] == case["expected"], f"case {i} ({case['note']})"


def test_sharded_limiter_matches_shared_oracle() -> None:
    """ShardedLimiter is a decision-parity port (see its module docstring):
    same admission sequence against the same oracle must produce the same
    allowed/remaining/retry_after_ms as RateLimiter and the Go/Node SDKs."""
    vectors = json.loads(VECTORS_PATH.read_text())

    clock = FixedClock()
    limiter = ShardedLimiter(clock, capacity=1_000)
    options = RateLimitOptions(
        requests_per_second=vectors["policy"]["requests_per_second"],
        burst=vectors["policy"]["burst"],
    )

    for i, step in enumerate(vectors["steps"]):
        clock.advance(step["advance_ms"])
        d = limiter.increment("conformance-key", options, float(step["n"]))
        assert d.allowed == step["allowed"], f"step {i} ({step['note']})"
        if step["allowed"]:
            assert d.remaining == step["remaining"], f"step {i} ({step['note']})"
        else:
            assert d.retry_after_ms == step["retry_after_ms"], f"step {i} ({step['note']})"


# ── Evidence chain ──
#
# Rule 13: parity claims must be conformance-tested, not assumed. The entry
# hash covers a compact-JSON payload; Go, Node, and Python must produce the
# same bytes, and therefore the same hashes and head, from the same inputs.
# The vectors were generated by the Go reference implementation.

EVIDENCE_VECTORS_PATH = (
    Path(__file__).resolve().parents[3] / "conformance" / "evidence_chain_vectors.json"
)


def test_conformance_evidence_chain() -> None:
    v = json.loads(EVIDENCE_VECTORS_PATH.read_text())
    assert GENESIS_PREV_HASH == v["genesis_prev_hash"]

    priv = private_key_from_raw(bytes.fromhex(v["seed_hex"]))
    chain = EvidenceChain()

    for i, c in enumerate(v["claims"]):
        receipt = issue_spend_receipt(
            priv,
            SpendReceiptClaims(
                key=c["key"],
                provider=c["provider"],
                model=c["model"],
                window_start_unix=c["window_start_unix"],
                window_end_unix=c["window_end_unix"],
                input_tokens=c["input_tokens"],
                output_tokens=c["output_tokens"],
                total_tokens=c["total_tokens"],
                estimated_cost_micro_usd=c["estimated_cost_micro_usd"],
            ),
            v["issued_at_unix"],
        )
        entry = chain.append(receipt)
        want = v["entries"][i]

        assert entry.seq == want["seq"], f"entry {i} seq"
        assert entry.prev_hash == want["prev_hash"], f"entry {i} prev_hash"
        assert (
            base64.b64encode(entry.receipt.signature).decode() == want["receipt_signature_b64"]
        ), f"entry {i} signature"
        assert entry.entry_hash == want["entry_hash"], f"entry {i} hash"

    assert chain.head == v["chain_head"]

    pkg = chain.export_evidence(v["issued_at_unix"])
    assert pkg.total_tokens == v["total_tokens"]
    assert pkg.total_estimated_cost_micro_usd == v["total_estimated_cost_micro_usd"]


# ── Streaming usage extraction ──
#
# Rule 13: parity claims must be conformance-tested, not assumed. These
# vectors exist because Python and Node silently reported NO usage for the
# single-usage-event case (the OpenAI-compatible shape) while Go handled it
# correctly — a real divergence that every per-language suite passed through.

SSE_VECTORS_PATH = Path(__file__).resolve().parents[3] / "conformance" / "sse_usage_vectors.json"


@pytest.mark.parametrize("case", json.loads(SSE_VECTORS_PATH.read_text())["cases"], ids=lambda c: c["name"])
def test_conformance_sse_usage(case: dict) -> None:
    usage = _extract_sse_usage(case["sse"])

    if not case["expect_found"]:
        assert usage is None or usage.total_tokens == 0, case["note"]
        return

    assert usage is not None, f"no usage extracted — {case['note']}"
    assert usage.input_tokens == case["expect_input_tokens"], case["note"]
    assert usage.output_tokens == case["expect_output_tokens"], case["note"]
    assert usage.total_tokens == case["expect_total_tokens"], case["note"]
