apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rateguard-keda
  namespace: default
  labels:
    app: rateguard
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: rateguard
  endpoints:
    - port: http
      path: /metrics/keda
      interval: 15s
      scrapeTimeout: 5s
